name: domain
description: Domain packages
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
